---
- name: Deploy Apache Docker Container
  hosts: localhost
  become: yes

  tasks:
    - name: Install Docker and Docker Compose
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Clone Docker Apache Container Repository
      git:
        repo: git@github.com:httpd/docker-httpd.git
        dest: /opt/docker-httpd
        version: main  # Specify the branch or tag if needed

    - name: Deploy Docker Container
      command: "docker-compose up -d"
      args:
        chdir: /opt/docker-httpd/2.4/

    - name: Open Port 80 for Apache
      ufw:
        rule: allow
        port: 80
