---
- name: Deploy Apache Docker Container
  hosts: localhost
  become: true

  tasks:
    - name: Deploy Apache Container
      docker_container:
        name: apache_container
        image: httpd:latest
        ports:
          - "80:80"
        restart_policy: always
        networks:
          - name: apache_network
      become: true

    - name: Create Docker Network
      docker_network:
        name: apache_network
        driver: bridge
        ipam_config:
          - subnet: 172.168.10.0/30
